services:
  chess-server:
    container_name: chess-api-local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "hml"
      NOME_CONTAINER: "chess-api-local"
      DATABASE_URL: "mysql://chessuser:chesspass@mariadb:3306/chessdb"
      REDIS_URL: "redis://:Redis2019!@redis:6379"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3001:3001"
    networks:
      - default

  mariadb:
    image: mariadb:11.4
    container_name: chess-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: chessdb
      MARIADB_USER: chessuser
      MARIADB_PASSWORD: chesspass
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mariadb

  redis:
    image: redis
    container_name: chess-redis
    command: redis-server --requirepass Redis2019!
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a Redis2019! ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

networks:
  default:
    name: chess-app-local-network

volumes:
  mariadb_data: