services:
  chess-server:
    image: gabrielzerio/chess-api:latest
    container_name: ${NOME_CONTAINER}
    environment:
      DATABASE_URL: "mysql://chessuser:chesspass@mariadb:3306/chessdb"
      # REDIS_URL: "redis://:Redis2019!@redis:6379"
      NODE_ENV: ${NODE_ENV}
      
    depends_on:
      mariadb:
        condition: service_healthy
      # redis:
      #   condition: service_started
    ports:
      - "3001:3001"
    networks:
      - nginx-net
      - default

  mariadb:
    image: mariadb:11.4
    container_name: chess-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: chessdb
      MARIADB_USER: chessuser
      MARIADB_PASSWORD: chesspass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mariadb
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3

  # redis:
  #   image: redis
  #   command: redis-server --requirepass Redis2019!
  #   ports:
  #     - "6379:6379"

volumes:
  mariadb_data:

networks:
  nginx-net:
    external: true