services:
  chess-server:
    image: chess-api-image
    container_name: chess-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - nginx-net

networks:
  nginx-net:
    external: true